{{- if and (not .Values.existingSecret) .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chainsettle-backend.fullname" . }}
  labels:
    {{- include "chainsettle-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
